# Generated by Django 4.0.3 on 2022-03-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_cd', models.AutoField(db_column='dept_cd', primary_key=True, serialize=False)),
                ('dept_name', models.CharField(db_column='dept_name', max_length=256, null=True)),
                ('dept_building', models.CharField(blank=True, db_column='dept_building', max_length=50)),
                ('faculty_cnt', models.IntegerField(db_column='faculty_cnt', null=True)),
                ('student_cnt', models.IntegerField(db_column='student_cnt', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subj_cd', models.AutoField(db_column='subj_cd', primary_key=True, serialize=False)),
                ('subj_name', models.CharField(db_column='subj_name', max_length=256, null=True)),
                ('room_no', models.CharField(blank=True, db_column='room_no', max_length=50)),
                ('strength', models.IntegerField(db_column='strength', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeptSubj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_cd', models.ForeignKey(db_column='dept_cd', on_delete=django.db.models.deletion.CASCADE, to='olp.department')),
                ('subj_cd', models.ForeignKey(db_column='subj_cd', on_delete=django.db.models.deletion.CASCADE, to='olp.subject')),
            ],
            options={
                'unique_together': {('dept_cd', 'subj_cd')},
            },
        ),
    ]
