# Generated by Django 4.0.3 on 2022-03-31 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.DecimalField(db_column='response', decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(db_column='course_name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='olp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(db_column='instructor_id', primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(db_column='student_name', max_length=256)),
                ('email', models.EmailField(db_column='email', max_length=256)),
                ('password', models.CharField(db_column='password', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(db_column='project_id', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='project_name', max_length=256)),
                ('content', models.TextField(db_column='content')),
                ('instructor_id', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='olp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(db_column='question_id', primary_key=True, serialize=False)),
                ('question_text', models.TextField(db_column='question_text')),
                ('correct_ans', models.DecimalField(db_column='correct_ans', decimal_places=3, max_digits=6)),
                ('marks', models.IntegerField(db_column='marks', default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(db_column='quiz_id', primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(db_column='quiz_name', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(db_column='student_id', primary_key=True, serialize=False)),
                ('student_name', models.CharField(db_column='student_name', max_length=256)),
                ('email', models.EmailField(db_column='email', max_length=256)),
                ('password', models.CharField(db_column='password', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(db_column='topic_id', primary_key=True, serialize=False)),
                ('topic_name', models.CharField(db_column='topic_name', max_length=256)),
                ('content', models.TextField(db_column='content')),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='olp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Working_On',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='olp.project')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='olp.student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='deptsubj',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deptsubj',
            name='dept_cd',
        ),
        migrations.RemoveField(
            model_name='deptsubj',
            name='subj_cd',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DeptSubj',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic_id',
            field=models.ForeignKey(db_column='topic_id', on_delete=django.db.models.deletion.CASCADE, to='olp.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(db_column='quiz_id', on_delete=django.db.models.deletion.CASCADE, to='olp.quiz'),
        ),
        migrations.AddField(
            model_name='enrolled',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='olp.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='olp.instructor'),
        ),
        migrations.AddField(
            model_name='answered',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='olp.question'),
        ),
        migrations.AddField(
            model_name='answered',
            name='student_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='olp.student'),
        ),
    ]
